site_name: PyDMConverter
repo_url: https://github.com/slaclab/pydm-converter-tool
repo_name: slaclab/pydm-converter-tool

nav:
  - Home: index.md
  - How To:
  - API Reference:

theme:
  name: material
  # custom_dir: overrides
  icon:
    repo: fontawesome/brands/github
  features:
    - navigation.top
    - navigation.tabs
    - navigation.indexes
    - navigation.footer
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: black
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode

extra:
  generator: false

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences

plugins:
  - search
