name: Bug report
description: Report an issue or bug with the project.
title: "[BUG] - "
labels: ["bug"]

body:
  - type: markdown
    attributes:
      value: |
        **Please provide a clear and concise description of the bug.**

  - type: textarea
    id: description
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is.
      placeholder: The bug occurs when...
    validations:
      required: true

  - type: textarea
    id: expected_behavior
    attributes:
      label: Expected behavior
      description: A clear and concise description of what you expected to happen.
      placeholder: I expected...
    validations:
      required: true

  - type: textarea
    id: steps_to_reproduce
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the bug.
      placeholder: |
        1. Go to...
        2. Click on...
        3. Scroll down to...
        4. See error
    validations:
      required: true

  - type: textarea
    id: possible_solution
    attributes:
      label: Possible solution (optional)
      description: Suggest a fix or reason for the bug, if you have any.
      placeholder: A possible solution could be...
    validations:
      required: false

  - type: input
    id: platform
    attributes:
      label: My platform
      description: Provide details about your system.
      placeholder: |
        OS Version: ...
        Python Version: ...
        Package Versions: ...
    validations:
      required: false

  - type: textarea
    id: additional_context
    attributes:
      label: Additional context
      description: Add any other context, links, or information about the bug.
      placeholder: Include logs, screenshots, or other details here.
    validations:
      required: false
