name: Feature request
description: Suggest a new feature or enhancement for the project.
title: "[FEATURE] - "
labels: ["enhancement"]

body:
  - type: markdown
    attributes:
      value: |
        **Please provide a clear and concise description of the feature you'd like to propose.**

  - type: textarea
    id: problem
    attributes:
      label: What's the problem this feature will solve?
      description: A clear and concise description of the problem or pain point.
      placeholder: This feature would solve...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Describe the solution you'd like
      description: A clear and concise description of what you want to happen.
      placeholder: The ideal solution would be...
    validations:
      required: true

  - type: textarea
    id: additional_context
    attributes:
      label: Additional context
      description: Add any other context, links, or resources to support your feature request.
      placeholder: Include any relevant links, screenshots, or references here.
    validations:
      required: false
