# This workflow will publish a new version of the documentation to the gh-pages branch

name: Publish Documentation

on:
  push:
    branches:
      - main

jobs:
  deploy:
    if: ${{ github.repository == 'slaclab/pydm-converter-tool' }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: [3.11]
    steps:
      - uses: actions/checkout@v3
      - uses: conda-incubator/setup-miniconda@v2
        with:
          miniforge-version: latest
          use-mamba: true
          python-version: ${{ matrix.python-version }}
          channels: conda-forge
          activate-environment: pydm-converter-tool-dev
          environment-file: environment.yml

      - name: Build Docs
        shell: bash -l {0}
        run: |
          mkdocs build

      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./site/
