name: Publish Python distributions to PyPI

on:
  release:
    types: [published]

jobs:
  publish-pypi:
    runs-on: ubuntu-latest
    environment: deployment
    permissions:
      id-token: write # IMPORTANT: this permission is mandatory for trusted publishing
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: 3.12
      - name: Install pypa/build
        run: |
          python -m pip install build --user
      - name: Build a source tarball
        run: |
          python -m build --sdist --outdir dist/ .
      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
